"""Adding tracking data and mappoint tables

Revision ID: f04111d13442
Revises: 09697b6b2d91
Create Date: 2025-01-17 18:14:04.138182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04111d13442'
down_revision: Union[str, None] = '09697b6b2d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('is_new_set', sa.Boolean(), nullable=False),
    sa.Column('is_new_record', sa.Boolean(), nullable=True),
    sa.Column('distance_covered', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_data_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tracking_data_id'], ['tracking_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_point')
    op.drop_table('tracking_data')
    # ### end Alembic commands ###
