services:
  main_db:
      image: postgres:13-bullseye
      restart: always
      pull_policy: always
      network_mode: "host"
      volumes:
        - pgdata1:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DATABASE}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5

  app:
    build:
      context: .
      dockerfile: ./workout-api/Dockerfile
    depends_on:
      main_db:
        condition: service_healthy
    network_mode: "host"

volumes:
  pgdata1: