services:
  main_db:
      image: postgres:13-bullseye
      restart: always
      pull_policy: always
      network_mode: "host"
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DATABASE}

  test_db:
      image: postgres:13-bullseye
      restart: always
      pull_policy: always
      network_mode: "host"
      volumes:
        - test_pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
        POSTGRES_USER: ${TEST_DB_USER}
        POSTGRES_DB: ${TEST_DATABASE}
        PGPORT: 5433

  app:
    build:
      context: .
      dockerfile: ./workout-api/Dockerfile
    network_mode: "host"

volumes:
  pgdata:
  test_pgdata: